language: ruby
rvm:
  - 2.3.0
cache: bundler
script: bundle exec rspec
bundler_args: --without production
services:
    - postgresql
before_script:
    - cp config/database.yml.travis config/database.yml
    - psql -c 'create database travis_ci_test;' -U postgres
